name = "PersistentCohomology"
uuid = "1871bf54-ef79-537f-b0b4-1ef9038f9ab8"
authors = ["Pietro Vertechi <pietro.vertechi@neuro.fchampalimaud.org>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
